// <auto-generated />
namespace KakPishetsya.Common.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddIndexesToWordsRulesUsers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddIndexesToWordsRulesUsers));
        
        string IMigrationMetadata.Id
        {
            get { return "201303202020379_AddIndexesToWordsRulesUsers"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
